import { Link } from 'react-router'
import PageHeader from '@/components/PageHeader'
import { Arrow, Button, Container, Eyebrow, Reveal, Section } from '@/components/ui'
import { comparison } from '@/data/offsets'
import { site } from '@/data/site'
import { usePageMeta } from '@/lib/hooks'

/**
 * The argument the rest of the site rests on.
 *
 * Nearly every organization with a net-zero claim is meeting it with unbundled
 * RECs, and most buyers have never been told that a REC is not required to
 * cause anything. Saying so plainly — while being fair to the instrument and
 * honest about how offsets fail — is the one piece of writing here that a reader
 * can't get from the dozen brokers also calling them.
 */
export default function RecsVsOffsets() {
  usePageMeta(
    'RECs vs. Carbon Offsets',
    'A Renewable Energy Certificate never has to prove it changed anything. A carbon offset does. The difference, point by point, and what it means for a net-zero claim.',
  )

  return (
    <>
      <PageHeader
        eyebrow="The case"
        title={
          <>
            One of these has to prove it{' '}
            <span className="text-forest-700 italic">changed something.</span>
          </>
        }
        lede={site.premise}
      >
        <Button to="/project-of-the-month">See this month’s project</Button>
        <Button to="/solutions/carbon-offsets" variant="secondary">
          How we choose projects
        </Button>
      </PageHeader>

      <Section>
        <Container size="narrow">
          <Reveal>
            <div className="rich-text">
              <p>
                A <strong>Renewable Energy Certificate</strong> represents one megawatt-hour of
                electricity generated by a renewable source somewhere in the United States. The
                certificate can be separated from the power itself and sold on its own, which is
                what most buyers purchase: an unbundled REC, most often from a wind farm in another
                state that was built years ago and is turning today regardless.
              </p>
              <p>
                RECs are easy to buy, cheap relative to almost anything else on a carbon inventory,
                and properly regulated — they are tracked and retired through generation attribute
                systems, so a certificate cannot be sold twice. None of that is in dispute, and none
                of it is the problem.
              </p>
              <p>
                The problem is what a REC is not asked to do.{' '}
                <strong>A REC does not have to stand the test of additionality.</strong> Nothing in
                the instrument requires the money you spend to cause a single additional tonne of
                carbon to be removed, avoided or destroyed. The wind farm was already there. The
                electrons were already flowing. You have bought the right to describe them as yours.
              </p>
              <p>
                A <strong>carbon offset</strong> is a different instrument with a different burden
                of proof. It is issued against a project that avoids, reduces or removes greenhouse
                gases; it is measured in tonnes of CO₂ equivalent rather than megawatt-hours; and
                the standards that issue it start from the question a REC never asks — would this
                have happened anyway?
              </p>
            </div>
          </Reveal>
        </Container>
      </Section>

      {/* The comparison itself. Two renderings of one dataset: a real table on
          desktop, where the row-by-row reading is the point, and stacked cards
          on phones, where a two-column table would be unreadable at any size. */}
      <Section tone="alt">
        <Container size="wide">
          <Reveal>
            <Eyebrow>Point by point</Eyebrow>
            <h2 className="font-display text-3xl leading-tight font-semibold text-[var(--ink)] sm:text-4xl">
              The same eight questions, asked of both
            </h2>
          </Reveal>

          <div className="mt-10 hidden overflow-hidden rounded-3xl border border-[var(--line)] bg-[var(--surface)] md:block">
            <table className="w-full border-collapse text-left text-sm">
              <caption className="sr-only">
                Renewable Energy Certificates compared with carbon offsets
              </caption>
              <thead>
                <tr className="bg-[var(--surface-alt)]">
                  <th scope="col" className="w-1/4 px-6 py-4 font-semibold text-[var(--ink)]">
                    Question
                  </th>
                  <th scope="col" className="px-6 py-4 font-semibold text-[var(--ink)]">
                    Renewable Energy Certificate
                  </th>
                  <th scope="col" className="px-6 py-4 font-semibold text-forest-800">
                    Carbon offset
                  </th>
                </tr>
              </thead>
              <tbody>
                {comparison.map((row) => (
                  <tr key={row.question} className="border-t border-[var(--line)] align-top">
                    <th scope="row" className="px-6 py-5 font-semibold text-[var(--ink)]">
                      {row.question}
                    </th>
                    <td className="px-6 py-5 leading-relaxed text-[var(--ink-muted)]">{row.rec}</td>
                    <td className="bg-forest-50/60 px-6 py-5 leading-relaxed text-[var(--ink-muted)]">
                      {row.offset}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>

          <div className="mt-10 grid gap-4 md:hidden">
            {comparison.map((row) => (
              <div
                key={row.question}
                className="rounded-2xl border border-[var(--line)] bg-[var(--surface)] p-6"
              >
                <h3 className="font-display text-lg font-semibold text-[var(--ink)]">
                  {row.question}
                </h3>
                <dl className="mt-4 space-y-4 text-sm">
                  <div>
                    <dt className="text-xs font-semibold tracking-[0.14em] text-[var(--ink-muted)] uppercase">
                      REC
                    </dt>
                    <dd className="mt-1 leading-relaxed text-[var(--ink-muted)]">{row.rec}</dd>
                  </div>
                  <div>
                    <dt className="text-xs font-semibold tracking-[0.14em] text-forest-700 uppercase">
                      Carbon offset
                    </dt>
                    <dd className="mt-1 leading-relaxed text-[var(--ink-muted)]">{row.offset}</dd>
                  </div>
                </dl>
              </div>
            ))}
          </div>
        </Container>
      </Section>

      <Section>
        <Container size="narrow">
          <Reveal>
            <div className="rich-text">
              <h2>Where this leaves a REC buyer</h2>
              <p>
                Nowhere embarrassing. RECs remain the standard way to make a Scope 2 claim, several
                reporting frameworks are built around them, and an organization that has been buying
                them has been doing what it was told to do by the market. If a compliance obligation
                or a reporting standard requires RECs, buy RECs.
              </p>
              <p>
                What we would ask is a narrower question:{' '}
                <strong>
                  how much of your budget is buying certificates that would exist without you?
                </strong>{' '}
                For most buyers the honest answer is all of it — and moving even a slice of that
                spend into vetted offsets changes what the money does, and gives your stakeholders
                something to read that isn’t a serial number.
              </p>

              <h2>Where this leaves us</h2>
              <p>
                Offsets have their own failure mode, and it is a real one. A project that promises
                not to log a forest nobody intended to log has sold a certificate as empty as any
                REC — emptier, because it came with a photograph and a story. That failure has
                happened often enough, and been reported on widely enough, that anyone selling
                offsets has to answer for it rather than change the subject.
              </p>
              <p>
                So we answer for it in public. Every project we put forward is written against a{' '}
                <Link to="/solutions/carbon-offsets">published checklist</Link> — additionality,
                baseline, permanence, leakage, double counting, co-benefits — and every write-up
                includes the fair objection to that project and our response to it. If we can’t
                state the objection, we don’t understand the project well enough to sell it.
              </p>
              <p>
                Very few people sell carbon offsets. They are harder work and thinner margin than
                selling electricity or gas, which is exactly why the field is empty and why the
                buyers who care are underserved.
              </p>
            </div>
          </Reveal>
        </Container>
      </Section>

      <Section tone="deep" className="py-16 sm:py-20">
        <Container size="narrow" className="text-center">
          <Reveal>
            <Eyebrow>Every month</Eyebrow>
            <h2 className="font-display text-3xl leading-tight font-semibold text-white sm:text-4xl">
              One project, examined in full
            </h2>
            <p className="mx-auto mt-5 max-w-xl leading-relaxed text-forest-200">
              The fastest way to see what an offset is — and what separates a good project from a
              certificate with a nice photograph — is to read one all the way through.
            </p>
            <div className="mt-9 flex flex-wrap justify-center gap-3">
              <Button to="/project-of-the-month">Project of the Month</Button>
              <Link
                to="/contact"
                className="group inline-flex items-center gap-2 rounded-full border border-white/20 px-6 py-3 text-sm font-semibold text-white transition-colors hover:border-white/45 hover:bg-white/5"
              >
                Talk about your inventory
                <Arrow />
              </Link>
            </div>
          </Reveal>
        </Container>
      </Section>
    </>
  )
}
